apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  endpoints:
    - port: web
      interval: 15s
