apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter
        ports:
        - containerPort: 9100
