apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos
  template:
    metadata:
      labels:
        app: thanos
    spec:
      containers:
      - name: thanos
        image: thanosio/thanos
        ports:
        - containerPort: 10901
